import * as fs from "fs";
import * as path from "path";

const filePath = path.join(process.cwd(), "client", "src", "lib", "statsData.ts");
let content = fs.readFileSync(filePath, "utf-8");

const categoryMappings: Record<string, string> = {
  "t-test-independent": "comparison",
  "paired-t-test": "comparison",
  "one-way-anova": "comparison",
  "two-way-anova": "comparison",
  "repeated-measures-anova": "comparison",
  "mann-whitney": "comparison",
  "wilcoxon-signed-rank": "comparison",
  "kruskal-wallis": "comparison",
  "friedman-test": "comparison",
  "welch-t-test": "comparison",
  "welch-anova": "comparison",
  "ancova": "comparison",
  "manova": "comparison",
  "pearson-correlation": "correlation",
  "spearman-correlation": "correlation",
  "partial-correlation": "correlation",
  "kendall-tau": "correlation",
  "point-biserial": "correlation",
  "intraclass-correlation": "correlation",
  "linear-regression": "regression",
  "multiple-regression": "regression",
  "logistic-regression": "regression",
  "poisson-regression": "regression",
  "ordinal-regression": "regression",
  "negative-binomial": "regression",
  "zero-inflated-poisson": "regression",
  "quantile-regression": "regression",
  "robust-regression": "regression",
  "probit-regression": "regression",
  "chi-square": "categorical",
  "fisher-exact": "categorical",
  "mcnemar-test": "categorical",
  "cochran-q": "categorical",
  "cramers-v": "categorical",
  "cohens-kappa": "categorical",
  "fleiss-kappa": "categorical",
  "linear-mixed-model": "mixed",
  "glmm": "mixed",
  "arima": "time-series",
  "exponential-smoothing": "time-series",
  "prophet": "time-series",
  "adf-test": "time-series",
  "granger-causality": "time-series",
  "ljung-box": "time-series",
  "var": "time-series",
  "kaplan-meier": "survival",
  "log-rank-test": "survival",
  "cox-regression": "survival",
  "accelerated-failure-time": "survival",
  "competing-risks": "survival",
  "random-survival-forest": "survival",
  "kmeans": "clustering",
  "hierarchical-clustering": "clustering",
  "dbscan": "clustering",
  "gaussian-mixture": "clustering",
  "pca": "dimension",
  "factor-analysis": "dimension",
  "tsne": "dimension",
  "umap": "dimension",
  "random-forest": "ml",
  "gradient-boosting": "ml",
  "lasso-ridge": "ml",
  "svm": "ml",
  "xgboost": "ml",
  "lightgbm": "ml",
  "catboost": "ml",
  "knn": "ml",
  "naive-bayes": "ml",
  "decision-tree": "ml",
  "elastic-net": "ml",
  "neural-network-mlp": "ml",
  "bootstrap": "resampling",
  "permutation-test": "resampling",
  "levene-test": "assumption",
  "bartlett-test": "assumption",
  "brown-forsythe": "assumption",
  "fligner-killeen": "assumption",
  "hartley-fmax": "assumption",
  "shapiro-wilk": "assumption",
  "kolmogorov-smirnov": "assumption",
  "anderson-darling": "assumption",
  "dagostino-pearson": "assumption",
  "durbin-watson": "assumption",
  "breusch-pagan": "assumption",
  "vif": "assumption",
  "tukey-hsd": "posthoc",
  "bonferroni": "posthoc",
  "holm-bonferroni": "posthoc",
  "benjamini-hochberg": "posthoc",
  "dunnett-test": "posthoc",
  "games-howell": "posthoc",
  "scheffe-test": "posthoc",
  "dunn-test": "posthoc",
  "bayesian-t-test": "bayesian",
  "bayesian-regression": "bayesian",
  "bayesian-anova": "bayesian",
  "cohens-d": "effectsize",
  "hedges-g": "effectsize",
  "eta-squared": "effectsize",
  "odds-ratio": "effectsize",
  "power-analysis": "planning",
};

for (const [testId, categoryId] of Object.entries(categoryMappings)) {
  const pattern = new RegExp(
    `(id: "${testId}",\\s*\\n\\s*name: "[^"]+",\\s*\\n\\s*description: "[^"]+",\\s*\\n\\s*assumptions: \\[[^\\]]*\\],\\s*\\n\\s*whenToUse: \\[[^\\]]*\\],\\s*\\n\\s*alternatives: \\[[^\\]]*\\],\\s*\\n\\s*methodFamily: "[^"]+",\\s*\\n\\s*category: ")([^"]+)(",)`,
    "g"
  );
  
  content = content.replace(pattern, `$1$2$3\n    categoryId: "${categoryId}",`);
}

fs.writeFileSync(filePath, content);
console.log("Added categoryId to all tests");
